### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wohlert** [wohlert/semi-supervised-pytorch#8]
The long term goal of the project:

- [ ] Update to torch 0.4.0
- [ ] Add blog posts of explanations of deep variational learning, semi-supervised learning, etc.
- [ ] Add GQN, DRAW, AIR models
- [ ] Rename repository to `variational-pytorch`
- [ ] Update to torch 1.0.0
